spring:
  application:
    name: servicedesk

  # =========================================================
  # PostgreSQL DataSource
  # =========================================================
  datasource:
    url: jdbc:postgresql://localhost:5432/servicedesk
    username: postgres
    password: 2w3a236fdj!
    driver-class-name: org.postgresql.Driver

  # =========================================================
  # JPA / Hibernate
  # =========================================================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Проверяем соответствие схемы Entity
    show-sql: false # Чтобы не мусорить в логах
    open-in-view: false

  # =========================================================
  # Flyway Database Migration
  # =========================================================
  flyway:
    enabled: true
    validate-on-migrate: true
    mixed: true

  # =========================================================
  # Web / MVC
  # =========================================================
  web:
    resources:
      add-mappings: false
  mvc:
    static-path-pattern: /static/**

  # =========================================================
  # File Upload Limits
  # =========================================================
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  # =========================================================
  # Redis
  # =========================================================

  data:
    redis:
      host: localhost
      port: 6739
      timeout: 2s
      repositories:
        enabled: false
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.SecurityAutoConfiguration

# =========================================================
# JWT Configuration
# =========================================================
jwt:
  secret: ${JWT_SECRET:mySecretKeyThatShouldBeChangedInProductionAndMustBeAtLeast256BitsLongForHS512}
  expiration: 86400000
  refresh-token:
    expiration-ms: 2592000000

app:
  upload:
    dir: ./uploads
    max-file-size-mb: 30
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
      - application/pdf
      - text/plain
      - application/msword

# =========================================================
# Logging
# =========================================================
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.flywaydb: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /docs
