spring:
  application:
    name: servicedesk

  # =========================================================
  # PostgreSQL DataSource
  # =========================================================
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/servicedesk}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456789}
    driver-class-name: org.postgresql.Driver

  # =========================================================
  # JPA / Hibernate
  # =========================================================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Проверка соответсвия схемы с Entity
    show-sql: false # Чтобы не мусорить в логах
    open-in-view: false

  # =========================================================
  # Flyway Database Migration
  # =========================================================
  flyway:
    enabled: true
    validate-on-migrate: true
    mixed: true

  # =========================================================
  # Web / MVC
  # =========================================================
  web:
    resources:
      add-mappings: false
  mvc:
    static-path-pattern: /static/**

  # =========================================================
  # File Upload Limits
  # =========================================================
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  # =========================================================
  # Redis
  # =========================================================

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s
      repositories:
        enabled: false
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.SecurityAutoConfiguration

  # =========================================================
  # RabbitMQ
  # Run RabbitMQ with Docker - docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
  # =========================================================
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

# =========================================================
# JWT Configuration
# =========================================================
jwt:
  secret: ${JWT_SECRET:mySecretKeyThatShouldBeChangedInProductionAndMustBeAtLeast256BitsLongForHS512}
  expiration: ${JWT_EXPIRATION:864000}
  refresh-token:
    expiration-ms: ${JWT_REFRESH_EXPIRATION:2592000000}

# =========================================================
# Telegram Bot (уведомления)
# =========================================================
telegram:
  token: ${TELEGRAM_BOT_TOKEN:}
  bot-username: ${TELEGRAM_BOT_USERNAME:ServiceDeskBot}
  enabled: ${TELEGRAM_ENABLED:false}

app:
  upload:
    dir: ./uploads
    max-file-size-mb: 30
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
      - application/pdf
      - text/plain
      - application/msword

# =========================================================
# Logging
# =========================================================
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.flywaydb: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /docs
