spring:
  application:
    name: servicedesk

  # =========================================================
  # PostgreSQL DataSource
  # =========================================================
  datasource:
    url: jdbc:postgresql://localhost:5432/servicedesk
    username: postgres
    password: 2w3a236fdj!
    driver-class-name: org.postgresql.Driver

  # =========================================================
  # JPA / Hibernate
  # =========================================================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Проверяем соответствие схемы Entity
    show-sql: false # Чтобы не мусорить в логах
    open-in-view: false

  # =========================================================
  # Flyway Database Migration
  # =========================================================
  flyway:
    enabled: true

  # =========================================================
  # Web / MVC
  # =========================================================
  web:
    resources:
      add-mappings: false
  mvc:
    static-path-pattern: /static/**

# =========================================================
# JWT Configuration
# =========================================================
jwt:
  secret: ${JWT_SECRET:mySecretKeyThatShouldBeChangedInProductionAndMustBeAtLeast256BitsLongForHS512}
  expiration: 86400000
  refresh-token:
    expiration-ms: 2592000000

app:
  upload:
    dir: ./uploads
    max-file-size-mb: 30
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
      - application/pdf
      - text/plain
      - application/msword
# =========================================================
# Logging (uncomment when needed)
# =========================================================
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.flywaydb: DEBUG
