spring:
  application:
    name: servicedesk

  # =========================================================
  # PostgreSQL DataSource
  # =========================================================
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # =========================================================
  # JPA / Hibernate
  # =========================================================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Проверка соответсвия схемы с Entity
    show-sql: false # Чтобы не мусорить в логах
    open-in-view: false

  # =========================================================
  # Flyway Database Migration
  # =========================================================
  flyway:
    enabled: true
    validate-on-migrate: true
    mixed: true

  # =========================================================
  # Web / MVC
  # =========================================================
  web:
    resources:
      add-mappings: false
  mvc:
    static-path-pattern: /static/**

  # =========================================================
  # File Upload Limits
  # =========================================================
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 45MB

  # =========================================================
  # Redis
  # =========================================================

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2s
      repositories:
        enabled: false
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.SecurityAutoConfiguration

  # =========================================================
  # RabbitMQ
  # Run RabbitMQ with Docker - docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
  # =========================================================
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

# =========================================================
# JWT Configuration
# =========================================================
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-token:
    expiration-ms: ${JWT_REFRESH_EXPIRATION}

app:
  upload:
    dir: ./uploads
    max-file-size-mb: 30
    wiki-max-attachments: 10
    avatar-max-size-mb: 10
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
      - application/pdf
      - text/plain
      - application/msword

# =========================================================
# Telegram Configuration
# =========================================================
telegram:
  token: ${TELEGRAM_BOT_TOKEN}
  bot-username: ${TELEGRAM_BOT_USERNAME}
  enabled: ${TELEGRAM_ENABLED}

# =========================================================
# MinIO Configuration
# =========================================================
minio:
  host: ${MINIO_HOST}
  port: ${MINIO_PORT}
  username: ${MINIO_USERNAME}
  password: ${MINIO_PASSWORD}
  chat-bucket: ${MINIO_CHAT_BUCKET}
  wiki-bucket: ${MINIO_WIKI_BUCKET}

# Run minio with docker:
# docker run -d --name minio -p 9000:9000 -p 9001:9001 \
# -e MINIO_ROOT_USER=${MINIO_USERNAME} -e MINIO_ROOT_PASSWORD=${MINIO_PASSWORD} \
# minio/minio server /data --console-address ":9001"

# =========================================================
# Springdoc configuration (OpenAPI)
# =========================================================
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /docs
